!
!---------------------------------------------------------------------
!
!Purpose:
! To extract a macro geometry and construct its geometry basic
! information.
!
!Copyright:
! Copyright (C) 2025 Ecole Polytechnique de Montreal.
! This library is free software; you can redistribute it and/or
! modify it under the terms of the GNU Lesser General Public
! License as published by the Free Software Foundation; either
! version 2.1 of the License, or (at your option) any later version
!
!Author(s):
! A. Hebert
!
!Parameters: input
! ITRACK   pointer to the tracking in IMACROth macro geometry.
! IFTRK    pointer to the TRACKING file in creation mode.
! IPRINT   print level.
! IMACRO   macro geometry index.
! NBSLIN   maximum number of segments in a single tracking line.
! RCUTOF   minimum distance between two surfacic elements.
! GG       global geometry basic information.
!
!Parameters: output
! LGINF        leakage flag (=.true. if no leakage).
! NBNODE_MACRO number of nodes in macro IMACRO.
! NBFLUX_MACRO number of fluxes in macro IMACRO.
! NSURF_MACRO  number of boundary surfaces in macro IMACRO.
! GG           geometry basic information.
!
!---------------------------------------------------------------------
!
SUBROUTINE MUSACG(ITRACK,IFTRK,IPRINT,IMACRO,NBSLIN,RCUTOF,GG,LGINF,NBNODE_MACRO, &
  & NBFLUX_MACRO,NSURF_MACRO)
  USE GANLIB
  USE PRECISION_AND_KINDS, ONLY : PDB, PI
  USE SAL_GEOMETRY_TYPES,  ONLY : T_G_BASIC,NIPAR,NRPAR,G_BC_TYPE,ISPEC,TYPGEO,NBFOLD,ALLSUR, &
                                  & LENGTHX,LENGTHY
  USE SAL_GEOMETRY_MOD,  ONLY : SAL130_2,SAL130_4,SAL130_6,SAL130_8,SAL130_10,SAL131_2, &
                                & SAL140,SAL160_2,SAL170,SALFOLD_3,SALFOLD_4
  USE SAL_NUMERIC_MOD,  ONLY : SAL141,FINDLC,DET_ROSETTA
  USE SAL_TRACKING_TYPES,  ONLY : PRTIND,NIPART,NRPART,EPS1
  !----
  !  Subroutine arguments
  !----
  TYPE(C_PTR) ITRACK
  INTEGER  IFTRK,IPRINT,IMACRO,NBNODE_MACRO,NBFLUX_MACRO,NSURF_MACRO
  REAL(PDB) RCUTOF
  LOGICAL LGINF,LGBC
  TYPE(T_G_BASIC) :: GG
  !----
  !  Local variables
  !----
  INTEGER, PARAMETER :: NSTATE=40
  INTEGER, PARAMETER :: FOUT=6
  INTEGER, PARAMETER ::  NDIM=2 ! NUMBER OF DIMENSIONS
  INTEGER, PARAMETER ::  MAXITR=6 ! NUMBER NUMBER OF PASSES
  REAL(PDB),PARAMETER :: EPS=1.0E-5_PDB
  INTEGER ISIZE1,ELEM,OK,TYPE,IPASS,INODE,MAXNODE,FOLDNUM
  REAL(PDB) :: THETA,AXY(2),X1,X2,Y1,Y2,DET1,DET2,XMIN,XMAX,YMIN,YMAX
  REAL(PDB) :: DGMESHX(2),DGMESHY(2)
  INTEGER, DIMENSION(NSTATE) :: I_STATE,IEDIMG
  CHARACTER(LEN=72) :: TEXT72
  CHARACTER(LEN=131) :: HSMG
  !----
  !  Allocatable arrays
  !----
  INTEGER, ALLOCATABLE, DIMENSION(:) :: NODE_LIST,ELEM_LIST,NODE_MACRO,ELEM_MACRO, &
    & AUX_ARR,SURF_MACRO,ICODE,IFOLD,IFOLD_GLOB,PERIM_SURF,SALTYPE,NMERGE_MACRO
  INTEGER, ALLOCATABLE, DIMENSION(:) :: NODE_LIST2,ELEM_LIST2,ELEM_MACRO2
  INTEGER, ALLOCATABLE, DIMENSION(:) :: ITAB ! LOCAL ARRAY
  REAL, ALLOCATABLE, DIMENSION(:) :: VOLUME,GALBED
  INTEGER, ALLOCATABLE, DIMENSION(:) :: MATALB,KEYMRG,IBC
  REAL(PDB), ALLOCATABLE, DIMENSION(:) :: VOLSUR
  REAL(PDB), ALLOCATABLE, DIMENSION(:,:,:) :: ALIGN
  TYPE(T_G_BASIC), ALLOCATABLE :: GG_MAC,GG_MAC2
  LOGICAL, ALLOCATABLE, DIMENSION(:) :: LFOLD
  !----
  !  Set isotropic tracking
  !----
  IF(IPRINT>0) WRITE(FOUT,'(/27H MUSACG: **** PROCESS MACRO,I5,5H ****)') IMACRO
  ISPEC=0
  !----
  ! Compute size of the global geometry
  !----
  XMIN=1.E10_PDB; YMIN=1.E10_PDB; XMAX=-1.E10_PDB; YMAX=-1.E10_PDB;
  DO ELEM=1,GG%NB_ELEM
    IF(GG%IPAR(1,ELEM)==1) THEN
      X1=GG%RPAR(1,ELEM); Y1=GG%RPAR(2,ELEM);
      XMIN=MIN(XMIN,X1); YMIN=MIN(YMIN,Y1); XMAX=MAX(XMAX,X1); YMAX=MAX(YMAX,Y1);
      X2=X1+GG%RPAR(3,ELEM); Y2=Y1+GG%RPAR(4,ELEM);
      XMIN=MIN(XMIN,X2); YMIN=MIN(YMIN,Y2); XMAX=MAX(XMAX,X2); YMAX=MAX(YMAX,Y2);
    ENDIF
  ENDDO
  LENGTHX=XMAX-XMIN; LENGTHY=YMAX-YMIN;
  !----
  !  GG_MAC allocation and extraction
  !----
  ALLOCATE(GG_MAC,NODE_LIST(GG%NB_NODE),ELEM_LIST(GG%NB_ELEM))
  CALL MUSMAC(IPRINT,IMACRO,0,0,GG,GG_MAC,NODE_LIST,ELEM_LIST)
  MAXNODE=2*MAXITR*GG_MAC%NB_NODE
  ALLOCATE(NODE_MACRO(MAXNODE),ELEM_MACRO(GG_MAC%NB_ELEM))
  NODE_MACRO(:MAXNODE)=0
  DO I=1,GG_MAC%NB_ELEM
    ELEM_MACRO(I) = FINDLC(ELEM_LIST,I)
  ENDDO
  DO I=1,GG_MAC%NB_NODE
    NODE_MACRO(I) = FINDLC(NODE_LIST,I)
  ENDDO
  !----
  !  Unfold the domain
  !----
  MAXGLOB=2*GG_MAC%NBBCDA*GG_MAC%NB_ELEM
  ALLOCATE(IFOLD_GLOB(MAXGLOB))
  IFOLD_GLOB(:GG_MAC%NB_ELEM)=(/ (ELEM, ELEM=1,GG_MAC%NB_ELEM) /)
  !----
  !  IPASS is the number of unfolding axes
  !----
  IPASS=0
  10 IPASS=IPASS+1
  IF(IPASS>MAXITR) CALL XABORT('MUSACG: MAXIMUM IPASS REACHED.')
  IF(IPRINT>2) THEN
    WRITE(FOUT,'(/25H MUSACG: -- PROCESS MACRO,I5,8H AT PASS,I2,3H --)') IMACRO,IPASS
  ENDIF
  THETA=0._PDB; AXY(1)=0._PDB; AXY(2)=0._PDB
  IF((TYPGEO==2).AND.(NBFOLD==6)) THEN
    THETA=-IPASS*PI/3._PDB; AXY(1)=XMIN+LENGTHX/2._PDB; AXY(2)=YMAX
  ELSE IF((TYPGEO==2).AND.(NBFOLD==3)) THEN
    THETA=-IPASS*2._PDB*PI/3._PDB; AXY(1)=XMIN+LENGTHX/3._PDB; AXY(2)=YMAX
  ENDIF
  !----
  !  Find if the perimeter contains an unfolding axis
  !----
  JMACRO=IMACRO
  ALLOCATE(LFOLD(GG_MAC%NBBCDA),ALIGN(3,3,GG_MAC%NBBCDA))
  ALIGN(:3,:3,:GG_MAC%NBBCDA)=1.0D0
  LFOLD(:GG_MAC%NBBCDA)=.FALSE.
  OUT1: DO IB=1,GG_MAC%NBBCDA
    DO I=1,GG_MAC%BCDATAREAD(IB)%NBER
      INDBC=GG_MAC%BCDATAREAD(IB)%ELEMNB(I)
      IF(INDBC==0) CYCLE
      IF(INDBC>GG_MAC%NB_ELEM) CALL XABORT('MUSACG: IFOLD overflow(1)')
      IF(IFOLD_GLOB(INDBC)>0) then
         IGLOB=ELEM_MACRO(IFOLD_GLOB(INDBC))
         IF((GG%IPAR(2,IGLOB)>0).AND.(GG%IPAR(3,IGLOB)>0)) CYCLE OUT1
      ELSE IF(IFOLD_GLOB(INDBC)<0) then
         IF(.NOT.ALLOCATED(GG_MAC2)) CALL XABORT('MUSACG: NEGATIVE IFOLD(1)')
         IGLOB=ELEM_MACRO2(-IFOLD_GLOB(INDBC))
         IF((GG%IPAR(2,IGLOB)>0).AND.(GG%IPAR(3,IGLOB)>0)) CYCLE OUT1
      ELSE
         CALL XABORT('MUSACG: NULL IFOLD(1)')
      ENDIF
      X1=GG_MAC%RPAR(1,INDBC); Y1=GG_MAC%RPAR(2,INDBC)
      X2=X1+GG_MAC%RPAR(3,INDBC); Y2=Y1+GG_MAC%RPAR(4,INDBC)
      ALIGN(1,1,IB)=X1; ALIGN(1,2,IB)=Y1
      ALIGN(2,1,IB)=X2; ALIGN(2,2,IB)=Y2
      EXIT
    ENDDO
    DO ELEM=1,GG_MAC%NB_ELEM
      IF(GG_MAC%IPAR(1,ELEM)==3) THEN
        IF(GG_MAC%MED(GG_MAC%IPAR(2,ELEM))==GG_MAC%MED(GG_MAC%IPAR(3,ELEM))) CYCLE
        CALL SAL141(3,GG_MAC%RPAR(:,ELEM),X1,Y1,1)
        CALL SAL141(3,GG_MAC%RPAR(:,ELEM),X2,Y2,2)
        ALIGN(3,1,IB)=X1; ALIGN(3,2,IB)=Y1;
        DET1 = DET_ROSETTA(ALIGN(1,1,IB),3)
        ALIGN(3,1,IB)=X2; ALIGN(3,2,IB)=Y2;
        DET2 = DET_ROSETTA(ALIGN(1,1,IB),3)
        LFOLD(IB)=((ABS(DET1).LE.1.0E-4).OR.(ABS(DET2).LE.1.0E-4))
        IF(LFOLD(IB)) CYCLE OUT1
      ENDIF
    ENDDO ! ELEM
  ENDDO OUT1
  !----
  !  Find the symmetric macro if a rotational symmetry is present. Exit extraneous macros.
  !----
  IF((IPASS==1).AND.(TYPGEO==2).AND.((NBFOLD==3).OR.(NBFOLD==6))) THEN
    DO IB=1,GG_MAC%NBBCDA
      IF(LFOLD(IB)) THEN
        IF(ABS(GG_MAC%BCDATAREAD(IB)%BCDATA(5)-PI/3._PDB).LE.EPS) THEN
          IGLOB=ELEM_MACRO(GG_MAC%BCDATAREAD(IB)%ELEMNB(1))
          CALL MUSSYM(GG,IGLOB,AXY,THETA,JMACRO)
          IF(IPRINT>2) WRITE(FOUT,'(/14H MUSACG: MACRO,I5,21H CORRESPONDS TO MACRO,I5,1H.)') JMACRO,IMACRO
          IF(JMACRO==0) CALL XABORT('MUSACG: UNABLE TO FIND A SYMMETRIC MACRO INDEX.') 
        ELSE
          IF(IPRINT>2) WRITE(FOUT,'(/14H MUSACG: MACRO,I5,15H IS EXTRANEOUS.)') IMACRO
          NBNODE_MACRO=0
          NSURF_MACRO=0
          RETURN
        ENDIF
        EXIT
      ENDIF
    ENDDO ! IB
  ENDIF
  !----
  !  GG_MAC2 allocation and extraction if a rotational symmetry is present
  !----
  IF((JMACRO>0).AND.(TYPGEO==2).AND.((NBFOLD==3).OR.(NBFOLD==6))) THEN
    DO IB=1,GG_MAC%NBBCDA
      IF(GG_MAC%BCDATAREAD(IB)%SALTYPE==3) THEN
        IF(ALLOCATED(GG_MAC2)) THEN
          CALL SALEND(GG_MAC2); DEALLOCATE(GG_MAC2)
          DEALLOCATE(ELEM_MACRO2)
        ENDIF
        ALLOCATE(GG_MAC2,NODE_LIST2(GG%NB_NODE),ELEM_LIST2(GG%NB_ELEM))
        INODE=GG_MAC%NB_NODE
        IMERG=GG_MAC%NB_FLUX
        IF(JMACRO==IMACRO) IMERG=0
        CALL MUSMAC(IPRINT,JMACRO,INODE,IMERG,GG,GG_MAC2,NODE_LIST2,ELEM_LIST2)
        IF(GG_MAC%NB_NODE+GG_MAC2%NB_NODE>MAXNODE) THEN
          WRITE(HSMG,'(16HMUSACG: NB_NODE=,I5,12H > MAXNODE =,I5,1H.)') GG_MAC%NB_NODE+GG_MAC2%NB_NODE,MAXNODE
          CALL XABORT(HSMG)
        ENDIF
        ALLOCATE(ELEM_MACRO2(GG_MAC2%NB_ELEM))
        DO I=1,GG_MAC2%NB_ELEM
          ELEM_MACRO2(I) = FINDLC(ELEM_LIST2,I)
        ENDDO
        DO I=1,GG_MAC2%NB_NODE
          NODE_MACRO(GG_MAC%NB_NODE+I) = FINDLC(NODE_LIST2,GG_MAC%NB_NODE+I)
        ENDDO
        DEALLOCATE(ELEM_LIST2,NODE_LIST2)
        EXIT
      ENDIF
    ENDDO ! IB
  ENDIF
  !----
  !  Printouts
  !----
  IF(IPRINT>2) THEN
    WRITE(FOUT,'(45H MUSACG: PERIMETERS BEFORE UNFOLDING AT PASS=,I2)') IPASS
    WRITE(FOUT,'(7H  PERIM,10I12,:/(7X,10I12))') (IB,IB=1,GG_MAC%NBBCDA)
    WRITE(FOUT,'(7H   TYPE,10I12,:/(7X,10I12))') GG_MAC%BCDATAREAD(:GG_MAC%NBBCDA)%SALTYPE
    WRITE(FOUT,'(7H      X,1P,10e12.4,:/(7X,10e12.4))') GG_MAC%BCDATAREAD(:GG_MAC%NBBCDA)%BCDATA(1)
    WRITE(FOUT,'(7H      Y,1P,10e12.4,:/(7X,10e12.4))') GG_MAC%BCDATAREAD(:GG_MAC%NBBCDA)%BCDATA(2)
    WRITE(FOUT,'(7H  ANGLE,1P,10e12.4,:/(7X,10e12.4))') GG_MAC%BCDATAREAD(:GG_MAC%NBBCDA)%BCDATA(5)*180._PDB/PI
    WRITE(FOUT,'(7H ALBEDO,1P,10e12.4,:/(7X,10e12.4))') GG_MAC%BCDATAREAD(:GG_MAC%NBBCDA)%BCDATA(6)
    WRITE(FOUT,'(7H UNFOLD,1P,10L12,:/(6X,10L12))') LFOLD(:GG_MAC%NBBCDA)
  ENDIF
  !----
  !  Unfold macro geometry (many times, if required)
  !----
  FOLDNUM=0
  DO IB=1,GG_MAC%NBBCDA
    IF(LFOLD(IB)) FOLDNUM=FOLDNUM+1
    ! if a macro side sitting on an unfolding axis has no circular interceptions, replace its boundary
    ! condition with a reflexion.
    IF(.NOT.LFOLD(IB)) GG_MAC%BCDATAREAD(IB)%SALTYPE=0
  ENDDO
  IF(FOLDNUM==GG_MAC%NBBCDA) CALL XABORT('MUSACG: YOU CANNOT UNFOLD ALL PERIMETERS OF A MACROCELL.')
  NBBCDA=GG_MAC%NBBCDA
  ALLOCATE(SALTYPE(NBBCDA))
  SALTYPE(:NBBCDA)=GG_MAC%BCDATAREAD(:NBBCDA)%SALTYPE
  OUT2: DO IB=1,NBBCDA
    IF(LFOLD(IB)) THEN
      IF((SALTYPE(IB)==3).AND.(NBFOLD==6)) THEN
        ! RA60 rotation
        IF(.NOT.ALLOCATED(GG_MAC2)) THEN
          WRITE(HSMG,'(13HMUSACG: MACRO,I5,25H IS NOT EXTRACTED (IPASS=,I2,2H).)') JMACRO,IPASS
          CALL XABORT(HSMG)
        ENDIF
        ISIZE1=GG_MAC%NB_ELEM+GG_MAC2%NB_ELEM
        ALLOCATE(IFOLD(ISIZE1))
        IFOLD(:ISIZE1)=0
        IF(FOLDNUM==1) THEN
          NPASS=1
          IF(IPASS>1) NPASS=5
        ELSE IF(FOLDNUM==2) THEN
          NPASS=5
        ELSE
          WRITE(HSMG,'(42HMUSACG: INVALID NUMBER OF UNFOLDIND AXES (,I3,10H) AT PASS=,I2,1H.)') FOLDNUM,IPASS
          CALL XABORT(HSMG)
        ENDIF
        IF(IPASS>NPASS) THEN
          WRITE(HSMG,'(14HMUSACG: IPASS=,I2,2H >,I2,13H OVERFLOW(1).)') IPASS,NPASS
          CALL XABORT(HSMG)
        ENDIF
        CALL SALFOLD_4(GG_MAC,GG_MAC2,IPASS,NPASS,THETA,AXY,IB,NBBCDA,IFOLD)
      ELSE IF((SALTYPE(IB)==3).AND.(NBFOLD==3)) THEN
        ! R120 rotation
        IF(.NOT.ALLOCATED(GG_MAC2)) THEN
          WRITE(HSMG,'(13HMUSACG: MACRO,I5,25H IS NOT EXTRACTED (IPASS=,I2,2H).)') JMACRO,IPASS
          CALL XABORT(HSMG)
        ENDIF
        ISIZE1=GG_MAC%NB_ELEM+GG_MAC2%NB_ELEM
        ALLOCATE(IFOLD(ISIZE1))
        IFOLD(:ISIZE1)=0
        IF(FOLDNUM==1) THEN
          NPASS=1
          IF(IPASS>1) NPASS=2
        ELSE IF(FOLDNUM==2) THEN
          NPASS=2
        ELSE
          WRITE(HSMG,'(42HMUSACG: INVALID NUMBER OF UNFOLDIND AXES (,I3,10H) AT PASS=,I2,1H.)') FOLDNUM,IPASS
          CALL XABORT(HSMG)
        ENDIF
        IF(IPASS>NPASS) THEN
          WRITE(HSMG,'(14HMUSACG: IPASS=,I2,2H >,I2,13H OVERFLOW(2).)') IPASS,NPASS
          CALL XABORT(HSMG)
        ENDIF
        CALL SALFOLD_4(GG_MAC,GG_MAC2,IPASS,NPASS,THETA,AXY,IB,NBBCDA,IFOLD)
      ELSE
        ! axial symmetry
        ISIZE1=2*GG_MAC%NB_ELEM
        ALLOCATE(IFOLD(ISIZE1))
        IFOLD(:ISIZE1)=0
        CALL SALFOLD_3(GG_MAC,IPASS,IB,NBBCDA,ALIGN,LFOLD,IFOLD)
      ENDIF
      DO ELEM=1,GG_MAC%NB_ELEM
        IF(ABS(IFOLD(ELEM))>MAXGLOB) CALL XABORT('MUSACG: IFOLD overflow(2)')
        IFOLD(ELEM)=SIGN(IFOLD_GLOB(ABS(IFOLD(ELEM))),IFOLD(ELEM))
      ENDDO
      IF(GG_MAC%NB_ELEM>MAXGLOB) CALL XABORT('MUSACG: IFOLD overflow(3)')
      IFOLD_GLOB(:GG_MAC%NB_ELEM)=IFOLD(:GG_MAC%NB_ELEM)
      DEALLOCATE(IFOLD)
      IF(SALTYPE(IB)==3) THEN
        DEALLOCATE(SALTYPE,ALIGN,LFOLD)
        GO TO 10
      ENDIF
    ENDIF
  ENDDO OUT2
  DEALLOCATE(SALTYPE,ALIGN,LFOLD)
  IF(IPRINT>2) THEN
    WRITE(FOUT,'(/35H MUSACG: PERIMETERS AFTER UNFOLDING)')
    WRITE(FOUT,'(7H  PERIM,10I12/(7X,10I12))') (IB,IB=1,GG_MAC%NBBCDA)
    WRITE(FOUT,'(7H   TYPE,10I12/(7X,10I12))') GG_MAC%BCDATAREAD(:GG_MAC%NBBCDA)%SALTYPE
    WRITE(FOUT,'(7H      X,1P,10e12.4/(7X,10e12.4))') GG_MAC%BCDATAREAD(:GG_MAC%NBBCDA)%BCDATA(1)
    WRITE(FOUT,'(7H      Y,1P,10e12.4/(7X,10e12.4))') GG_MAC%BCDATAREAD(:GG_MAC%NBBCDA)%BCDATA(2)
    WRITE(FOUT,'(7H  ANGLE,1P,10e12.4/(7X,10e12.4))') GG_MAC%BCDATAREAD(:GG_MAC%NBBCDA)%BCDATA(5)*180._PDB/PI
    WRITE(FOUT,'(7H ALBEDO,1P,10e12.4/(7X,10e12.4))') GG_MAC%BCDATAREAD(:GG_MAC%NBBCDA)%BCDATA(6)
  ENDIF
  DO ELEM=1,GG_MAC%NB_ELEM
    IF(ABS(IFOLD_GLOB(ELEM))>MAXGLOB) CALL XABORT('MUSACG: IFOLD overflow(4)')
    IF(IFOLD_GLOB(ELEM)>0) THEN
      IFOLD_GLOB(ELEM)=ELEM_MACRO(IFOLD_GLOB(ELEM))
    ELSE IF(IFOLD_GLOB(ELEM)<0) THEN
      IF(.NOT.ALLOCATED(GG_MAC2)) CALL XABORT('MUSACG: NEGATIVE IFOLD(2)')
      IFOLD_GLOB(ELEM)=ELEM_MACRO2(-IFOLD_GLOB(ELEM))
    ELSE
      CALL XABORT('MUSACG: NULL IFOLD(2)')
    ENDIF
  ENDDO
  IF(ALLOCATED(GG_MAC2)) THEN
    CALL SALEND(GG_MAC2); DEALLOCATE(GG_MAC2)
    DEALLOCATE(ELEM_MACRO2)
  ENDIF
  NBNODE_MACRO=GG_MAC%NB_NODE
  NBFLUX_MACRO=GG_MAC%NB_FLUX
  IF(IPRINT>2) WRITE(6,'(/15H MUSACG: IFOLD=,20I5/(15X,20I5))') IFOLD_GLOB(:GG_MAC%NB_ELEM)
  IF(IPRINT>1) WRITE(FOUT,*) 'MUSACG: after unfolding -- NB_ELEM=',GG_MAC%NB_ELEM,' NB_PERIM=',GG_MAC%NBBCDA
  IF(IPRINT>5) THEN
    !*    print surfacic file
    WRITE(FOUT,'(5H--cut,70(1H-),I5)') IMACRO
    WRITE(FOUT,'(5HBEGIN)')
    WRITE(FOUT,'(42H* typgeo nbfold nbnode nbelem nbmacr nbreg)')
    WRITE(FOUT,'(6I7)') 0,0,GG_MAC%NB_NODE,GG_MAC%NB_ELEM,GG_MAC%NB_MACRO,GG_MAC%NB_FLUX
    WRITE(FOUT,'(20H* index  kndex  prec)')
    WRITE(FOUT,'(4I7)') 0,0,1
    WRITE(FOUT,'(18H* eps         eps0)')
    WRITE(FOUT,'(1P,2E18.9)') 1.0E-03,1.0E-05
    WRITE(FOUT,'(20H* num_of_region/mesh)')
    WRITE(FOUT,'(10I7)') (GG_MAC%NUM_MERGE(I),I=1,GG_MAC%NB_NODE)
    WRITE(FOUT,'(13H* macro names)')
    WRITE(FOUT,'(4(3x,a10,2x))') (GG_MAC%NAME_MACRO(I),I=1,GG_MAC%NB_MACRO)
    WRITE(FOUT,'(35H* macro_order_index_per_flux_region)')
    WRITE(FOUT,'(10I7)') (GG_MAC%NUM_MACRO(I),I=1,GG_MAC%NB_FLUX)
    DO ELEM=1,GG_MAC%NB_ELEM
      TYPE=GG_MAC%IPAR(1,ELEM)
      WRITE(FOUT,'(7h elem =,I6)') ELEM
      WRITE(FOUT,'(22H*type    node-   node+)')
      WRITE(FOUT,'(3I6)') (GG_MAC%IPAR(I,ELEM),I=1,3)
      WRITE(FOUT,'(63H*cx            cy            ex_or_R       ey_or_theta1  theta2)')
      IF(TYPE<=2) THEN
        WRITE(FOUT,'(1P,5E18.9)') (GG_MAC%RPAR(I,ELEM),I=1,5)
      ELSE IF(TYPE==3) THEN
        WRITE(FOUT,'(1P,5E18.9)') (GG_MAC%RPAR(I,ELEM),I=1,3),GG_MAC%RPAR(4,ELEM)*180._PDB/PI, &
                                (GG_MAC%RPAR(5,ELEM)-GG_MAC%RPAR(4,ELEM))*180._PDB/PI
      ENDIF
    ENDDO
    WRITE(FOUT,'(40H*defaul  nbbcda  allsur  divsur  ndivsur)')
    WRITE(FOUT,'(1P,5I8)') GG_MAC%DEFAUL,GG_MAC%NBBCDA,ALLSUR,0,0
    WRITE(FOUT,'(17H*albedo  deltasur)')
    WRITE(FOUT,'(1P,2E18.9)') GG_MAC%ALBEDO,0.0
    DO IB=1,GG_MAC%NBBCDA
      WRITE(FOUT,'(37H particular boundary condition number,i12)') IB
      WRITE(FOUT,'(13H*type    nber)')
      WRITE(FOUT,'(1P,2I8)') GG_MAC%BCDATAREAD(IB)%SALTYPE,GG_MAC%BCDATAREAD(IB)%NBER
      WRITE(FOUT,'(14H*elems(1,nber))')
      WRITE(FOUT,'(1P,10I8)') (GG_MAC%BCDATAREAD(IB)%ELEMNB(I),I=1,GG_MAC%BCDATAREAD(IB)%NBER)
      IF(GG_MAC%BCDATAREAD(IB)%SALTYPE<=1) THEN
        WRITE(FOUT,'(7H*albedo)')
        WRITE(FOUT,'(1P,E18.9)') GG_MAC%BCDATAREAD(IB)%BCDATA(6)
      ELSE IF(GG_MAC%BCDATAREAD(IB)%SALTYPE==2) THEN
        WRITE(FOUT,'(11H*tx      ty)')
        WRITE(FOUT,'(1P,3E18.9)') GG_MAC%BCDATAREAD(IB)%BCDATA(1:2),0.0
      ELSE IF(GG_MAC%BCDATAREAD(IB)%SALTYPE>=3) THEN
        WRITE(FOUT,'(22H*cx      cy      angle)')
        WRITE(FOUT,'(1P,3E18.9)') GG_MAC%BCDATAREAD(IB)%BCDATA(1:2), &
        & GG_MAC%BCDATAREAD(IB)%BCDATA(5)*180._PDB/PI
      ENDIF
    ENDDO
    WRITE(FOUT,'(12H* mil(nbreg))')
    WRITE(FOUT,'(10I7)') (GG_MAC%MED(I),I=1,GG_MAC%NB_NODE)
    WRITE(FOUT,'(3HEND)')
    WRITE(FOUT,'(5H--cut,70(1H-),I5)') IMACRO
  ENDIF
  !****
  !*    compute node perimeters for the macro
  ALLOCATE (GG_MAC%PPERIM_NODE(GG_MAC%NB_NODE+1),STAT=OK)
  IF(OK/=0) CALL XABORT('MUSACG: not enough memory PPERIM_NODE')
  ALLOCATE(AUX_ARR(2*GG_MAC%NB_ELEM))
  CALL SAL130_2(GG_MAC%NB_ELEM,GG_MAC%NB_NODE,GG_MAC%IPAR,GG_MAC%PPERIM_NODE, &
     GG_MAC%PERIM_NODE,AUX_ARR)
  !
  !*    - compute number of bc's per 2D macro,
  !       NB_BC2 counts total nber of 2D bc's
  !     - compute IBC2_ELEM, keep relative 2D bc nber to elements
  !     - allocation : 2D bc structures
  !                    2D perimeter structure for a macro
  !     - get list of elements in 2d macro perimeter
  ALLOCATE(GG_MAC%IBC2_ELEM(GG_MAC%NB_ELEM),GG_MAC%ISURF2_ELEM(GG_MAC%NB_ELEM))
  CALL SAL130_4(GG_MAC%NB_ELEM,NN,GG_MAC%IPAR,GG_MAC%IBC2_ELEM,AUX_ARR)
  GG_MAC%NB_BC2 = NN
  GG_MAC%NALBG = GG_MAC%NBBCDA
  !*    allocate bcdata
  ALLOCATE (GG_MAC%BCDATA(6,GG_MAC%NALBG), STAT=OK)
  IF(OK/=0) CALL XABORT('MUSACG: not enough memory R')
  DO IB=1,GG_MAC%NALBG
    GG_MAC%BCDATA(:6,IB)=GG_MAC%BCDATAREAD(IB)%BCDATA(:6)
  ENDDO
  !
  !*    put default value in all bc elements:
  ALLOCATE(GG_MAC%TYPE_BC2(NN),GG_MAC%IDATA_BC2(NN),GG_MAC%PERIM_MAC2(NN),STAT=OK)
  IF(OK/=0) CALL XABORT('MUSACG: not enough memory I,R')
  GG_MAC%PERIM_MAC2(1:NN) = AUX_ARR(1:NN)
  GG_MAC%NPERIM_MAC2 = NN
  DEALLOCATE(AUX_ARR)
  GG_MAC%TYPE_BC2(:NN) = 0
  CALL SAL131_2(GG_MAC%NB_ELEM,GG_MAC%DEFAUL,GG_MAC%IPAR,GG_MAC%IBC2_ELEM,GG_MAC%TYPE_BC2, &
    & GG_MAC%IDATA_BC2)
  ITBC=0
  IF(GG_MAC%NBBCDA>0)THEN
    DO I=1,GG_MAC%NBBCDA
      ITBC=ITBC+1
      TYPE=0
      !
      !           modify notation for boundary conditions
      NBER=GG_MAC%BCDATAREAD(I)%NBER
      DO J=1,NBER
          ELEM=GG_MAC%BCDATAREAD(I)%ELEMNB(J)
          IF(ELEM>GG_MAC%NB_ELEM.OR.ELEM<=0) CALL XABORT('MUSACG: unknown bc element')
          !        get local surface nber
          IB=GG_MAC%IBC2_ELEM(ELEM)
          IF(IB==0) CYCLE
          LGBC=GG_MAC%IPAR(2,ELEM)<=0
          II=0
          IF(LGBC)THEN
            II=2
          ELSE
            LGBC=GG_MAC%IPAR(3,ELEM)<=0
            IF(LGBC) II=3
          ENDIF
          IF(.NOT.LGBC) THEN
            WRITE(*,*) 'ib :',IB,' elem :',ELEM
            WRITE(*,*) 'GG_MAC%IPAR(:,ELEM) :',GG_MAC%IPAR(:,ELEM)
            WRITE(HSMG,'(33HMUSACG: wrong bc element in macro,I5)') IMACRO
            CALL XABORT(HSMG)
          ENDIF
          !              put bc type
          GG_MAC%IPAR(II,ELEM)=G_BC_TYPE(TYPE)
          GG_MAC%TYPE_BC2(IB)=G_BC_TYPE(TYPE)
          !              put bc data position :
          GG_MAC%IDATA_BC2(IB)=ITBC
      ENDDO
    ENDDO
  ENDIF
  !
  !*    - set BCDATA position for surfaces of type G_BC_TYPE(-1)
  !     - compute the nber of surfaces (type -1,0,-12,-13,-14,-15) : nbsur2
  !     - allocate structures for the surfaces
  !     - compute surf_mac2
  ALLOCATE(AUX_ARR(GG_MAC%NB_ELEM))
  AUX_ARR(:GG_MAC%NB_ELEM)=0
  GG_MAC%ISURF2_ELEM(:GG_MAC%NB_ELEM)=0
  GG_MAC%NB_ELEM=GG_MAC%NB_ELEM
  NSURF_MACRO=0
  DO IB=1,GG_MAC%NB_BC2
    !           relative element nber
    IELEM=GG_MAC%PERIM_MAC2(IB)
    !           count 2D surfaces number
    IF(GG_MAC%TYPE_BC2(IB)==G_BC_TYPE(-1) .OR. GG_MAC%TYPE_BC2(IB)==G_BC_TYPE(0) .OR. &
      & GG_MAC%TYPE_BC2(IB)==G_BC_TYPE(1)) THEN
      NSURF_MACRO=NSURF_MACRO+1
      AUX_ARR(NSURF_MACRO)=IB
      GG_MAC%ISURF2_ELEM(IELEM)=NSURF_MACRO
    ELSE
      GG_MAC%ISURF2_ELEM(IELEM)=0
    ENDIF
  ENDDO
  GG_MAC%NB_SURF2 = NSURF_MACRO
  ALLOCATE(SURF_MACRO(NSURF_MACRO))
  IF(NSURF_MACRO>0) THEN
    DO I=1,NSURF_MACRO
      ELEM = FINDLC(GG_MAC%ISURF2_ELEM,I)
      IF(ELEM>GG_MAC%NB_ELEM) CALL XABORT('MUSACG: ELEM_MACRO OVERFLOW.')
      SURF_MACRO(I) = IFOLD_GLOB(ELEM)
    ENDDO
    ALLOCATE (GG_MAC%IBC2_SURF2(NSURF_MACRO),GG_MAC%IELEM_SURF2(NSURF_MACRO),STAT=OK)
    IF(OK/=0) CALL XABORT('MUSACG: NOT ENOUGH MEMORY I,R')
    GG_MAC%IBC2_SURF2(1:NSURF_MACRO)=AUX_ARR(1:NSURF_MACRO)
    !
    !     - define IELEM_SURF2 ???
    ALLOCATE(GG_MAC%SURF2(GG_MAC%NB_SURF2),STAT = OK)
    IF(OK /= 0) CALL XABORT('MUSACG: not enough memory I,R')
    CALL SAL130_6(GG_MAC%NB_SURF2,GG_MAC%IBC2_SURF2,GG_MAC%PERIM_MAC2, &
    & GG_MAC%IELEM_SURF2)
  ELSE
    NULLIFY(GG_MAC%IBC2_SURF2)
  ENDIF
  IF(IPRINT>2) THEN
    WRITE(FOUT,'(/38H MUSACG: NODE CORRESPONDANCE FOR MACRO,I5)') IMACRO
    WRITE(FOUT,'(7H  LOCAL,20I5,:/(7X,20I5))') (I,I=1,GG_MAC%NB_NODE)
    WRITE(FOUT,'(7H  MERGE,20I5,:/(7X,20I5))') (GG_MAC%NUM_MERGE(I),I=1,GG_MAC%NB_NODE)
    WRITE(FOUT,'(7H GLOBAL,20I5,:/(7X,20I5))') (NODE_MACRO(I),I=1,GG_MAC%NB_NODE)
    WRITE(FOUT,'(7H  MERGE,20I5,:/(7X,20I5))') (GG%NUM_MERGE(NODE_MACRO(I)),I=1,GG_MAC%NB_NODE)
  ENDIF
  ALLOCATE(NMERGE_MACRO(GG_MAC%NB_FLUX))
  DO I=1,GG_MAC%NB_NODE
    II=GG_MAC%NUM_MERGE(I)
    IF(II>GG_MAC%NB_FLUX) CALL XABORT('MUSACG: NMERGE_MACRO OVERFLOW.')
    NMERGE_MACRO(II)=GG%NUM_MERGE(NODE_MACRO(I))
  ENDDO
  CALL LCMSIX(ITRACK,'SURFACIC_TMP',1)
    IF(NSURF_MACRO>0) CALL LCMPUT(ITRACK,'SURF_MACRO',NSURF_MACRO,1,SURF_MACRO)
    CALL LCMPUT(ITRACK,'GLOBAL_MERGE',GG_MAC%NB_FLUX,1,NMERGE_MACRO)
  CALL LCMSIX(ITRACK,'          ',2)
  DEALLOCATE(NMERGE_MACRO,IFOLD_GLOB,ELEM_MACRO,NODE_MACRO,AUX_ARR,SURF_MACRO)
  !
  !* topological check
  ALLOCATE (GG_MAC%VOL_NODE(GG_MAC%NB_NODE), STAT=OK)
  IF(OK/=0) CALL XABORT('MUSACG: not enough memory VOL')
  CALL SAL140(GG_MAC%NB_NODE,GG_MAC%RPAR,GG_MAC%IPAR,GG_MAC%PPERIM_NODE,GG_MAC%PERIM_NODE)
  !
  !*    volumes, surfaces, put local nbers in node, and read media:
  CALL SAL160_2(GG_MAC%NB_ELEM,GG_MAC%IPAR,GG_MAC%RPAR,GG_MAC%VOL_NODE,GG_MAC%ISURF2_ELEM, &
      GG_MAC%NB_SURF2,GG_MAC%SURF2)
  !
  !*    printout basic domain
  CALL SAL170(GG_MAC)
  !----
  !  Save MUST tracking information on LCM
  !----
  CALL LCMSIX(ITRACK,'GEOMETRY  ',1)
  CALL LCMPUT(ITRACK,'NB_ELEM   ',1,1,GG_MAC%NB_ELEM)
  CALL LCMPUT(ITRACK,'NIPAR     ',1,1,SIZE(GG_MAC%IPAR,1))
  CALL LCMPUT(ITRACK,'IPAR    ',SIZE(GG_MAC%IPAR),1,GG_MAC%IPAR)
  CALL LCMPUT(ITRACK,'RPAR    ',SIZE(GG_MAC%RPAR),4,GG_MAC%RPAR)
  CALL LCMPUT(ITRACK,'ISURF2_ELEM ',SIZE(GG_MAC%ISURF2_ELEM),1,GG_MAC%ISURF2_ELEM)
  CALL LCMPUT(ITRACK,'NB_NODE   ',1,1,GG_MAC%NB_NODE)
  CALL LCMPUT(ITRACK,'VOL_NOD   ',GG_MAC%NB_NODE,4,GG_MAC%VOL_NODE)
  CALL LCMPUT(ITRACK,'NB_SURF2  ',1,1,GG_MAC%NB_SURF2)
  IF(GG_MAC%NBBCDA>0) THEN
    LGINF = .TRUE.
    DO IB=1, GG_MAC%NBBCDA
      LGINF = LGINF .AND. (GG_MAC%BCDATAREAD(IB)%BCDATA(6) == 1._PDB)
    ENDDO
  ELSE
    LGINF = (GG_MAC%ALBEDO == 1._PDB)
  ENDIF
  IF(GG_MAC%NB_SURF2 > 0) THEN
    CALL LCMPUT(ITRACK,'IBC2_SURF2  ',SIZE(GG_MAC%IBC2_SURF2),1,GG_MAC%IBC2_SURF2)
    CALL LCMPUT(ITRACK,'IELEM_SURF2 ',SIZE(GG_MAC%IELEM_SURF2),1,GG_MAC%IELEM_SURF2)
    CALL LCMPUT(ITRACK,'SURF2       ',SIZE(GG_MAC%SURF2),4,GG_MAC%SURF2)
  ENDIF
  CALL LCMPUT(ITRACK,'NPERIM_MAC2 ',1,1,GG_MAC%NPERIM_MAC2)
  CALL LCMPUT(ITRACK,'PERIM_MAC2  ',SIZE(GG_MAC%PERIM_MAC2),1,GG_MAC%PERIM_MAC2)
  CALL LCMPUT(ITRACK,'PERIM_NODE  ',SIZE(GG_MAC%PERIM_NODE),1,GG_MAC%PERIM_NODE)
  CALL LCMPUT(ITRACK,'PPERIM_NODE ',SIZE(GG_MAC%PPERIM_NODE),1,GG_MAC%PPERIM_NODE)
  CALL LCMPUT(ITRACK,'BC_DATA_DIM2',1,1,SIZE(GG_MAC%BCDATA,2))
  CALL LCMPUT(ITRACK,'NB_BC2    ',1,1,GG_MAC%NB_BC2)
  CALL LCMSIX(ITRACK,' ',2) ! come back to father directory
  !----
  ! Print tracking object directory
  !----
  IF(IPRINT>4) THEN
    WRITE(FOUT,'(/14H MUSACG: MACRO,I6.6,20H GEOMETRY DIRECTORY:)') IMACRO
    CALL LCMLIB(ITRACK)
    CALL LCMSIX(ITRACK,'GEOMETRY',1)
    CALL LCMLIB(ITRACK)
    CALL LCMSIX(ITRACK,' ',2)
  ENDIF
  !----
  ! store the STATE VECTOR
  !----
  NREG=MAXVAL(GG_MAC%NUM_MERGE)
  LEAK=1
  IF(.NOT.LGINF) LEAK=0 ! reset the leakage flag
  CALL LCMGET(ITRACK,'STATE-VECTOR',I_STATE)   
  I_STATE(1) = NREG ! number of regions
  I_STATE(2) = NREG ! number of unknowns in DRAGON
  I_STATE(3) = LEAK ! 1 = absent leakage, 0 leakage
  I_STATE(4) = MAXVAL(GG_MAC%MED(1:GG_MAC%NB_NODE)) ! maximum number of mixture
  I_STATE(5) = GG_MAC%NB_SURF2 ! number of outer surface
  I_STATE(9) = ISPEC
  I_STATE(24)= 0
  NSOUT=GG_MAC%NB_SURF2
  CALL LCMPUT(ITRACK,'STATE-VECTOR',NSTATE,1,I_STATE)   
  !
  ! fill-in medium number per region
  ALLOCATE(ITAB(NREG),VOLUME(NREG), STAT =OK)
  IF(OK /= 0) CALL XABORT('MUSACG: failure to allocate integer ITAB')
  ! fill in MATCOD
  DO J=1,GG_MAC%NB_NODE
    ITAB(GG_MAC%NUM_MERGE(J)) = GG_MAC%MED(J)
  ENDDO
  CALL LCMPUT(ITRACK,'MATCOD',NREG,1,ITAB(1:NREG) )
  ! fill-in KEYFLX per region
  ITAB(1:NREG)=(/ (I,I=1,NREG) /)
  CALL LCMPUT(ITRACK,'MERGE',NREG,1,ITAB)
  CALL LCMPUT(ITRACK,'KEYFLX',NREG,1,ITAB)
  ! fill-in volumes per region
  VOLUME(:NREG) =0.
  DO I=1,GG_MAC%NB_NODE
    VOLUME(GG_MAC%NUM_MERGE(I)) = VOLUME(GG_MAC%NUM_MERGE(I)) + REAL(GG_MAC%VOL_NODE(I))
  ENDDO
  CALL LCMPUT(ITRACK,'VOLUME',NREG,2,VOLUME)
  DEALLOCATE(VOLUME,ITAB)

  ! useful values in SAL_TRACKING_TYPES module
  NFREG=GG_MAC%NB_NODE
  CALL LCMSIX(ITRACK,'NXTRecords',1)
    DGMESHX=(/ 1.E10_PDB , -1.E10_PDB /)
    DGMESHY=(/ 1.E10_PDB , -1.E10_PDB /)
    DO ELEM=1,GG_MAC%NB_ELEM
      DGMESHX(1)=MIN(DGMESHX(1),GG_MAC%RPAR(1,ELEM))
      DGMESHX(2)=MAX(DGMESHX(2),GG_MAC%RPAR(1,ELEM))
      DGMESHY(1)=MIN(DGMESHY(1),GG_MAC%RPAR(2,ELEM))
      DGMESHY(2)=MAX(DGMESHY(2),GG_MAC%RPAR(2,ELEM))
    ENDDO
    CALL LCMPUT(ITRACK,'G00000001SMX',2,4,DGMESHX)
    CALL LCMPUT(ITRACK,'G00000001SMY',2,4,DGMESHY)
    IEDIMG(:NSTATE)=0
    IEDIMG(1)=NDIM
    IEDIMG(2)=0 ! Cartesian geometry
    IF(TYPGEO==8) IEDIMG(2)=2 ! Isocel geometry with specular reflection
    IF(TYPGEO==9) IEDIMG(2)=3 ! Hexagonal geometry with translation
    IF(TYPGEO==10) IEDIMG(2)=4 ! Isocel geometry with RA60 symmetry
    IF(TYPGEO==11) IEDIMG(2)=5 ! Lozenge geometry with R120 rotation
    IF(TYPGEO==12) IEDIMG(2)=6 ! S30 geometry with specular reflection
    IEDIMG(5)=1 ! 1 cellule
    IEDIMG(13)=1 ! 1 cellule
    IEDIMG(14)=1 ! 1 cellule
    IEDIMG(22)=NSOUT ! number of external surfaces for this geometry
    IEDIMG(23)=NFREG ! number of regions for this geometry
    IEDIMG(25)=GG_MAC%NB_NODE
    CALL LCMPUT(ITRACK,'G00000001DIM',NSTATE,1,IEDIMG)
  CALL LCMSIX(ITRACK,' ',2)  ! come back to father directory
  !----
  ! process boundary conditions
  !----
  IF(IPRINT>1) WRITE(FOUT,*) 'number of merged regions,surfaces,nodes',NREG,NSOUT,NFREG
  ALLOCATE(MATALB(-NSOUT:NFREG),VOLSUR(-NSOUT:NFREG),KEYMRG(-NSOUT:NFREG))
  CALL LCMGET(ITRACK,'MATCOD',MATALB(1))
  ALLOCATE(VOLUME(NREG))
  CALL LCMGET(ITRACK,'VOLUME',VOLUME)
  VOLSUR(1:NREG)=VOLUME(:NREG)
  DEALLOCATE(VOLUME)
  ! boundary conditions structures
  ALLOCATE(ICODE(GG_MAC%NALBG),GALBED(GG_MAC%NALBG))
  ICODE(1:GG_MAC%NALBG)=(/ (-I,I=1,GG_MAC%NALBG) /)
  GALBED(:GG_MAC%NALBG)=REAL(GG_MAC%ALBEDO)
  DO I=1,NSOUT
    KEYMRG(-I)=-I
    VOLSUR(-I)=GG_MAC%SURF2(I)
    INDEX=GG_MAC%IDATA_BC2(GG_MAC%IBC2_SURF2(I))
    IF(INDEX==0) THEN
      ! Use the default albedo
      MATALB(-I)=-1
      GALBED(1)=REAL(GG_MAC%ALBEDO)
    ELSE
      IF(INDEX > GG_MAC%NALBG) THEN
        CALL XABORT('MUSACG: Albedo array overflow(2).')
      ENDIF
      MATALB(-I)=-INDEX
      IF(SIZE(GG_MAC%BCDATA) > 0) THEN
        GALBED(INDEX)=REAL(GG_MAC%BCDATA(6,INDEX))
      ELSE
        GALBED(INDEX)=REAL(GG_MAC%ALBEDO)
      ENDIF
    ENDIF
  ENDDO
  MATALB(0)=0
  KEYMRG(0)=0
  VOLSUR(0)=0._PDB
  KEYMRG(1:NREG)=(/ (I,I=1,NREG) /)
  !
  IF(IPRINT>2) THEN
     CALL PRINDM('VOLUME',VOLSUR(-NSOUT),NREG+NSOUT+1)
     CALL PRINIM('MATALB',MATALB(-NSOUT),NREG+NSOUT+1)
     CALL PRINIM('KEYMRG',KEYMRG(-NSOUT),NREG+NSOUT+1)
  ENDIF
  IF(IPRINT>1) THEN
     CALL PRINIM('ICODE ',ICODE(1),GG_MAC%NALBG)
     CALL PRINAM('GALBED',GALBED(1),GG_MAC%NALBG)
  ENDIF
  !----
  ! fill in tracking LCM object in excelt format
  !----
  TEXT72='SAL TRACKING'
  CALL LCMPTC(ITRACK,'TITLE',72,TEXT72)
  CALL LCMPUT(ITRACK,'ICODE',GG_MAC%NALBG,1,ICODE)
  CALL LCMSIX(ITRACK,'NXTRecords',1)
  CALL LCMPUT(ITRACK,'SAreaRvolume',NREG+NSOUT+1,4,VOLSUR(-NSOUT))
  CALL LCMPUT(ITRACK,'MATALB',NREG+NSOUT+1,1,MATALB(-NSOUT))
  CALL LCMPUT(ITRACK,'KEYMRG',NREG+NSOUT+1,1,KEYMRG(-NSOUT))
  CALL LCMSIX(ITRACK,' ',2)
  IF(NSOUT>0) THEN
     ALLOCATE(IBC(NSOUT))
     IBC(1:NSOUT)=(/ (I,I=1,NSOUT) /)
     CALL LCMPUT(ITRACK,'BC-REFL+TRAN',NSOUT,1,IBC)
     DEALLOCATE(IBC)
  ENDIF
  ALLOCATE(PERIM_SURF(GG_MAC%NB_ELEM))
  PERIM_SURF(:GG_MAC%NB_ELEM)=0
  DO IB=1,GG_MAC%NBBCDA
    DO I=1,GG_MAC%BCDATAREAD(IB)%NBER
      ELEM=GG_MAC%BCDATAREAD(IB)%ELEMNB(I)
      IF(ELEM>GG_MAC%NB_ELEM) CALL XABORT('MUSACG: inconsistent perimeter(1)')
      ISURF=GG_MAC%ISURF2_ELEM(ELEM)
      IF(ISURF>NSURF_MACRO) CALL XABORT('MUSACG: inconsistent perimeter(2)')
      PERIM_SURF(ISURF)=IB
    ENDDO
  ENDDO
  CALL LCMPUT(ITRACK,'MATCOD',NREG,1,MATALB(1))
  CALL LCMPUT(ITRACK,'ALBEDO',GG_MAC%NALBG,2,GALBED)
  CALL LCMPUT(ITRACK,'PERIM_SURF',NSURF_MACRO,1,PERIM_SURF)
  DEALLOCATE(PERIM_SURF,GALBED,ICODE)
  DEALLOCATE(KEYMRG,VOLSUR,MATALB)
  !----
  !  Track macro geometry IMACR
  !----
  PRTIND=IPRINT
  F_GEO=FGEO
  EPS1=1.E-5_PDB
  IF(RCUTOF>0._PDB) THEN
    EPS1=RCUTOF
    IF(PRTIND>0) WRITE(*,*) "MUSACG: set eps1 to ",EPS1
  ENDIF
  IGTRK=1
  CALL SALTCG(ITRACK, IFTRK, IPRINT, IGTRK, NBSLIN, GG_MAC)
  !----
  !  Release allocated memory for macro IMACR
  !----
  CALL SALEND(GG_MAC)
  DEALLOCATE(GG_MAC, STAT= OK)
  IF(OK /= 0) CALL XABORT('MUSACG: failure to deallocate GG_MAC')
  CALL LCMVAL(ITRACK,' ')
  !
  CONTAINS
    !
    !---------------------------------------------------------------------
    !
    !Purpose:
    ! Find the symmetric macro index with rotational symmetries.
    !
    !Parameters: input
    ! GG     global geometry basic information
    ! IGLOB  boundary element index in GG
    ! AXY    rotation center
    ! THETA  rotation angle
    !
    !Parameters: output
    ! JMACRO symmetric macro index
    !
    !---------------------------------------------------------------------
    !
    SUBROUTINE MUSSYM(GG,IGLOB,AXY,THETA,JMACRO)
      USE SAL_GEOMETRY_TYPES, ONLY : T_G_BASIC
      USE SAL_GEOMETRY_MOD, ONLY : SALROT
      !----
      !  Subroutine arguments
      !----
      INTEGER  IGLOB,JMACRO
      REAL(PDB) AXY(2),THETA
      TYPE(T_G_BASIC) :: GG
      !----
      !  Local variables
      !----
      INTEGER IB2,I2,ELEM
      REAL(PDB) X1,Y1,X2,Y2,X3,Y3,X5,Y5
      LOGICAL L1,L2
      REAL(PDB),PARAMETER :: EPS=1.0E-5_PDB
      !
      JMACRO=0
      X1=GG%RPAR(1,IGLOB); Y1=GG%RPAR(2,IGLOB)
      X2=X1+GG%RPAR(3,IGLOB); Y2=Y1+GG%RPAR(4,IGLOB)
      DO IB2=1,GG%NBBCDA
        IF(GG%BCDATAREAD(IB2)%SALTYPE/=3) CYCLE
        DO I2=1,GG%BCDATAREAD(IB2)%NBER
          ELEM=GG%BCDATAREAD(IB2)%ELEMNB(I2)
          IF(ELEM==0) CYCLE
          IF(GG%IPAR(1,ELEM)/=1) CALL XABORT('MUSSYM: INVALID BOUNDARY ELEMENT.')
          X3=GG%RPAR(1,ELEM); Y3=GG%RPAR(2,ELEM)
          CALL SALROT(AXY(1),AXY(2),THETA,X3,Y3,X5,Y5)
          L1=(ABS(X1-X5)<EPS).AND.(ABS(Y1-Y5)<EPS)
          L2=(ABS(X2-X5)<EPS).AND.(ABS(Y2-Y5)<EPS)
          IF(L1.OR.L2) THEN
            IF(GG%IPAR(2,ELEM)>0) THEN
              JMACRO=GG%NUM_MACRO(GG%NUM_MERGE(GG%IPAR(2,ELEM)))
              RETURN
            ELSE IF(GG%IPAR(3,ELEM)>0) THEN
              JMACRO=GG%NUM_MACRO(GG%NUM_MERGE(GG%IPAR(3,ELEM)))
              RETURN
            ENDIF
          ENDIF
        ENDDO
      ENDDO
   END SUBROUTINE MUSSYM
END SUBROUTINE MUSACG
