!
!---------------------------------------------------------------------
!
!Purpose:
! To extract a macro geometry.
!
!Copyright:
! Copyright (C) 2025 Ecole Polytechnique de Montreal.
! This library is free software; you can redistribute it and/or
! modify it under the terms of the GNU Lesser General Public
! License as published by the Free Software Foundation; either
! version 2.1 of the License, or (at your option) any later version
!
!Author(s):
! A. Hebert
!
!Parameters: input
! IPRINT   print level.
! IMACRO   macro geometry index.
! INODE    number of nodes in a previously extracted macro.
! IMERG    number of fluxes in a previously extracted macro.
! GG       geometry basic information.
!
!Parameters: output
! GG_MAC       geometry basic information for IMACRO.
! NODE_LIST    node indices in macro IMACRO.
! ELEM_LIST    element indices in macro IMACRO.
!
!---------------------------------------------------------------------
!
SUBROUTINE MUSMAC(IPRINT,IMACRO,INODE,IMERG,GG,GG_MAC,NODE_LIST,ELEM_LIST)
  USE PRECISION_AND_KINDS, ONLY : PDB
  USE SAL_GEOMETRY_TYPES,  ONLY : T_G_BASIC,NIPAR,NRPAR
  USE SAL_NUMERIC_MOD,  ONLY : FINDLC,DET_ROSETTA
  !----
  !  Subroutine arguments
  !----
  TYPE(T_G_BASIC) :: GG,GG_MAC
  INTEGER  IPRINT,IMACRO,INODE,IMERG,NODE_LIST(GG%NB_NODE),ELEM_LIST(GG%NB_ELEM)
  !----
  !  Local variables
  !----
  INTEGER, PARAMETER :: FOUT=6
  INTEGER NBNODE_MACRO,NELEM_MACRO,ELEM,OK
  REAL(PDB) :: X1,X2,Y1,Y2,DET1,DET2
  !----
  !  Allocatable arrays
  !----
  INTEGER, ALLOCATABLE, DIMENSION(:) :: NODE_MACRO,ELEM_MACRO,PERIM_MACRO,SALTYPE
  REAL(PDB), ALLOCATABLE, DIMENSION(:) :: ANGLE,ALBEDO
  REAL(PDB), ALLOCATABLE, DIMENSION(:,:,:) :: ALIGN
  !----
  !  List of nodes and surface elements in IMACRO
  !----
  IF(IPRINT>1) WRITE(FOUT,'(/A,I5,A)') ' MUSMAC: **** EXTRACT MACRO',IMACRO,' ****'
  NULLIFY(GG_MAC%IBC2_ELEM,GG_MAC%IBC2_SURF2,GG_MAC%BCDATAREAD)
  ELEM_LIST(:GG%NB_ELEM) = 0
  NODE_LIST(:GG%NB_NODE) = -9999
  I=0
  DO ELEM=1,GG%NB_ELEM
    I2=GG%IPAR(2,ELEM)
    I3=GG%IPAR(3,ELEM)
    IF((I2>0).AND.(ELEM_LIST(ELEM) == 0)) THEN
      IF(GG%NUM_MACRO(GG%NUM_MERGE(I2)) == IMACRO) THEN
        I=I+1
        ELEM_LIST(ELEM)=I
        NODE_LIST(I2)=1
        IF(I3>0) THEN
          IF(GG%NUM_MACRO(GG%NUM_MERGE(I3)) == IMACRO) NODE_LIST(I3)=1
        ENDIF
      ENDIF
    ENDIF
    IF((I3>0).AND.(ELEM_LIST(ELEM) == 0)) THEN
      IF(GG%NUM_MACRO(GG%NUM_MERGE(I3)) == IMACRO) THEN
        I=I+1
        ELEM_LIST(ELEM)=I
        NODE_LIST(I3)=1
      ENDIF
    ENDIF
  ENDDO ! ELEM
  NBNODE_MACRO = INODE
  DO J=1,GG%NB_NODE
    IF(NODE_LIST(J) /= -9999) THEN
      NBNODE_MACRO = NBNODE_MACRO+1
      NODE_LIST(J) = NBNODE_MACRO
    ENDIF
  ENDDO
  NELEM_MACRO=I
  ALLOCATE(NODE_MACRO(NBNODE_MACRO),ELEM_MACRO(NELEM_MACRO))
  DO I=1,NELEM_MACRO
    ELEM_MACRO(I) = FINDLC(ELEM_LIST,I)
  ENDDO
  DO I=1,NBNODE_MACRO
    NODE_MACRO(I) = FINDLC(NODE_LIST,I)
  ENDDO
  !----
  !  Find perimeter. Three points are colinear if the determinant is zero.
  !----
  ALLOCATE(PERIM_MACRO(NELEM_MACRO),ANGLE(NELEM_MACRO),ALBEDO(NELEM_MACRO),SALTYPE(NELEM_MACRO))
  ALLOCATE(ALIGN(3,3,NELEM_MACRO))
  ALIGN(:3,3,:NELEM_MACRO)=1.0_PDB
  PERIM_MACRO(:NELEM_MACRO)=0
  NPERIM=0
  ITER0: DO I=1,NELEM_MACRO
    ELEM = ELEM_MACRO(I)
    DO J=1,NBNODE_MACRO
      IF(GG%IPAR(2,ELEM).EQ.NODE_MACRO(J)) GO TO 10
    ENDDO
    GO TO 20
    10 DO J=1,NBNODE_MACRO
      IF(GG%IPAR(3,ELEM).EQ.NODE_MACRO(J)) CYCLE ITER0
    ENDDO
    20 IF(GG%IPAR(1,ELEM)==1) THEN
      X1=GG%RPAR(1,ELEM); Y1=GG%RPAR(2,ELEM);
      X2=X1+GG%RPAR(3,ELEM); Y2=Y1+GG%RPAR(4,ELEM);
      DO J=1,NPERIM
        ALIGN(3,1,J)=X1; ALIGN(3,2,J)=Y1;
        DET1 = DET_ROSETTA(ALIGN(1,1,J),3)
        ALIGN(3,1,J)=X2; ALIGN(3,2,J)=Y2;
        DET2 = DET_ROSETTA(ALIGN(1,1,J),3)
        IF((ABS(DET1).LE.1.0E-4).AND.(ABS(DET2).LE.1.0E-4)) THEN
          PERIM_MACRO(I) = J
          CYCLE ITER0
        ENDIF
      ENDDO
      NPERIM=NPERIM+1
      PERIM_MACRO(I) = NPERIM
      ANGLE(NPERIM)=ATAN((Y2-Y1)/(X2-X1))
      IF(ABS(ANGLE(NPERIM)).LE.1.0E-5) ANGLE(NPERIM)=0.0
      ALIGN(1,1,NPERIM)=X1; ALIGN(1,2,NPERIM)=Y1
      ALIGN(2,1,NPERIM)=X2; ALIGN(2,2,NPERIM)=Y2
      ! Recover albedo from global geometry
      ALBEDO(NPERIM)=1.0
      SALTYPE(NPERIM)=0
      DO IB=1,GG%NBBCDA
        J = FINDLC(GG%BCDATAREAD(IB)%ELEMNB,ELEM)
        IF(J.NE.0) SALTYPE(NPERIM)=GG%BCDATAREAD(IB)%SALTYPE
      ENDDO
      DO IB=1,GG%NBBCDA
        J = FINDLC(GG%BCDATAREAD(IB)%ELEMNB,ELEM)
        IF(J.EQ.1) THEN
          ALBEDO(NPERIM)=GG%BCDATAREAD(IB)%BCDATA(6)
          EXIT
        ENDIF
      ENDDO
    ENDIF
  ENDDO ITER0
  !----
  !  Printouts
  !----
  IF(IPRINT>2) THEN
    WRITE(FOUT,'(/39H MUSMAC: IPAR VALUES IN GLOBAL GEOMETRY)')
    WRITE(FOUT,'(5H ELEM,20I5,:/(5X,20I5))') ELEM_MACRO(:NELEM_MACRO)
    WRITE(FOUT,'(5H TYPE,20I5,:/(5X,20I5))') GG%IPAR(1,ELEM_MACRO(:NELEM_MACRO))
    WRITE(FOUT,'(5H    -,20I5,:/(5X,20I5))') GG%IPAR(2,ELEM_MACRO(:NELEM_MACRO))
    WRITE(FOUT,'(5H    +,20I5,:/(5X,20I5))') GG%IPAR(3,ELEM_MACRO(:NELEM_MACRO))
  ENDIF
  !----
  !  Create volume and merge information
  !----
  ALLOCATE(GG_MAC%VOL_NODE(NBNODE_MACRO),GG_MAC%MED(NBNODE_MACRO),GG_MAC%NAME_MACRO(1), &
  & GG_MAC%NUM_MERGE(NBNODE_MACRO), STAT=OK)
  IF(OK/=0) CALL XABORT('MUSMAC: not enough memory I,R')
  GG_MAC%NAME_MACRO(1) = 'MACR000001'
  GG_MAC%VOL_NODE(:NBNODE_MACRO) = 0.0
  GG_MAC%MED(:NBNODE_MACRO) = 0
  GG_MAC%NUM_MERGE(:NBNODE_MACRO) = 0
  DO I=1,NBNODE_MACRO
    J = NODE_MACRO(I)
    IF(J.EQ.0) CYCLE
    GG_MAC%VOL_NODE(I) = GG%VOL_NODE(J)
    GG_MAC%MED(I) = GG%MED(J)
    GG_MAC%NUM_MERGE(I) = GG%NUM_MERGE(J)
  ENDDO
  NBFLUX_MACRO = IMERG+GG%NB_FLUX
  DO I=GG%NB_FLUX,1,-1
    J = FINDLC(GG_MAC%NUM_MERGE,I)
    IF(J>0) CYCLE
    DO J=1,NBNODE_MACRO
      IF(GG_MAC%NUM_MERGE(J)>I) GG_MAC%NUM_MERGE(J)=GG_MAC%NUM_MERGE(J)-1
    ENDDO
    NBFLUX_MACRO = NBFLUX_MACRO-1
  ENDDO
  DO I=1,NBNODE_MACRO
    IF(GG_MAC%NUM_MERGE(I).NE.0) GG_MAC%NUM_MERGE(I)=IMERG+GG_MAC%NUM_MERGE(I)
  ENDDO
  IF(IPRINT>2) THEN
    WRITE(FOUT,'(/32H MUSMAC: number of flux in macro,I6.6,1H=,I5)') IMACRO,NBFLUX_MACRO
    WRITE(FOUT,'(5H NODE,20I5,:/(5X,20I5))') (I,I=1,NBNODE_MACRO)
    WRITE(FOUT,'(5H MIX ,20I5,:/(5X,20I5))') (GG_MAC%MED(I),I=1,NBNODE_MACRO)
    WRITE(FOUT,'(5H MERG,20I5,:/(5X,20I5))') (GG_MAC%NUM_MERGE(I),I=1,NBNODE_MACRO)
  ENDIF
  ALLOCATE(GG_MAC%NUM_MACRO(NBFLUX_MACRO), STAT=OK)
  IF(OK/=0) CALL XABORT('MUSMAC: not enough memory NUM_MACRO')
  GG_MAC%NUM_MACRO(:NBFLUX_MACRO) = 1
  !----
  !  Fill the GG_MAC tracking structure
  !----
  GG_MAC%NBBCDA = NPERIM
  GG_MAC%NB_ELEM = NELEM_MACRO
  GG_MAC%NB_NODE = NBNODE_MACRO
  GG_MAC%NB_FLUX = NBFLUX_MACRO
  GG_MAC%NB_MACRO = 1
  GG_MAC%DEFAUL = GG%DEFAUL
  ALLOCATE(GG_MAC%IPAR(NIPAR,NELEM_MACRO),GG_MAC%RPAR(NRPAR,NELEM_MACRO), STAT=OK)
  IF(OK/=0) CALL XABORT('MUSMAC: not enough memory I,R')
  GG_MAC%IPAR(:3,:GG_MAC%NB_ELEM)=0
  GG_MAC%RPAR(:3,:GG_MAC%NB_ELEM)=0.0
  DO ELEM=1, GG_MAC%NB_ELEM
    GG_MAC%IPAR(1,ELEM) = GG%IPAR(1,ELEM_MACRO(ELEM)) ! elem type
    I = GG%IPAR(2,ELEM_MACRO(ELEM)) ! node-
    J = FINDLC(NODE_MACRO,I)
    IF(J>0) THEN
      GG_MAC%IPAR(2,ELEM) = J
    ELSE
      GG_MAC%IPAR(3,ELEM) = MIN(I,0)
    ENDIF
    I = GG%IPAR(3,ELEM_MACRO(ELEM)) ! node+
    J = FINDLC(NODE_MACRO,I)
    IF(J>0) THEN
      GG_MAC%IPAR(3,ELEM) = J
    ELSE
      GG_MAC%IPAR(3,ELEM) = MIN(I,0)
    ENDIF
    GG_MAC%RPAR(:NRPAR,ELEM) = GG%RPAR(:NRPAR,ELEM_MACRO(ELEM))
  ENDDO
  IF(IPRINT>2) THEN
    WRITE(FOUT,'(/38H MUSMAC: IPAR VALUES IN MACRO GEOMETRY)')
    WRITE(FOUT,'(5H ELEM,20I5,:/(5X,20I5))') (I,I=1,GG_MAC%NB_ELEM)
    WRITE(FOUT,'(5H TYPE,20I5,:/(5X,20I5))') GG_MAC%IPAR(1,:GG_MAC%NB_ELEM)
    WRITE(FOUT,'(5H    -,20I5,:/(5X,20I5))') GG_MAC%IPAR(2,:GG_MAC%NB_ELEM)
    WRITE(FOUT,'(5H    +,20I5,:/(5X,20I5))') GG_MAC%IPAR(3,:GG_MAC%NB_ELEM)
  ENDIF
  GG_MAC%ALBEDO=GG%ALBEDO
  ALLOCATE(GG_MAC%BCDATAREAD(GG_MAC%NBBCDA))
  DO IB=1, GG_MAC%NBBCDA
    GG_MAC%BCDATAREAD(IB)%NBER = COUNT(PERIM_MACRO(:NELEM_MACRO) == IB)
    ALLOCATE(GG_MAC%BCDATAREAD(IB)%ELEMNB(GG_MAC%BCDATAREAD(IB)%NBER))
    J=0
    DO I=1,NELEM_MACRO
      IF(PERIM_MACRO(I) == IB) THEN
        J=J+1
        GG_MAC%BCDATAREAD(IB)%ELEMNB(J) = I
      ENDIF
    ENDDO
    GG_MAC%BCDATAREAD(IB)%BCDATA(1) = ALIGN(1,1,IB)
    GG_MAC%BCDATAREAD(IB)%BCDATA(2) = ALIGN(1,2,IB)
    GG_MAC%BCDATAREAD(IB)%BCDATA(3) = COS(ANGLE(IB))
    GG_MAC%BCDATAREAD(IB)%BCDATA(4) = SIN(ANGLE(IB))
    GG_MAC%BCDATAREAD(IB)%BCDATA(5) = ANGLE(IB)
    GG_MAC%BCDATAREAD(IB)%BCDATA(6) = ALBEDO(IB)
    GG_MAC%BCDATAREAD(IB)%SALTYPE = SALTYPE(IB)
  ENDDO
  DEALLOCATE(ALIGN,SALTYPE,ALBEDO,ANGLE,PERIM_MACRO)
END SUBROUTINE MUSMAC
