#!/usr/bin/python3
"""
Subversion post-commit hook which copy (append) the issue-tracking information
to a new (or existing) card-index in the /issues/ directory. A commit of this
information is performed.
"""
#Author: Alain Hebert, Ecole Polytechnique, 2026.

import os, sys

def main(repos, rev):
  # Recover the revision data:
  sys.stderr.write("post-commit: rev=" + rev + "\n")
  message = os.popen("svnlook log -r " + rev + " " + repos).readline().strip('\n')
  sys.stderr.write ("commit message=" + message + "\n")
  if message[11:] != ': Issue-tracking commit' and message[11:] != ':':
    # Recover the existing card-index
    fileName = message[:11]
    scratch_dir = '/tmp/post-issues/'
    if os.path.isdir(scratch_dir):
      os.system("chmod -R 777 scratch_dir")
      os.system("rm -r scratch_dir")
    os.system("mkdir scratch_dir")
    os.system("svn checkout file://" + repos + "/issues/ " + scratch_dir)
    isThere = False
    revmax = int(os.popen("svnlook youngest " + repos).readline().strip('\n'))
    for k in range(revmax):
      if os.popen("svnlook log -r " + str(k+1) + " " + repos).readline().strip('\n') == fileName:
        isThere = True
        break
    transaction = scratch_dir + "/" + fileName
    sys.stderr.write ("issue card exists=" + str(isThere) + "\n")
    sys.stderr.write ("transaction file=" + transaction + "\n")
    if not isThere:
      # Create a new card-index
      f = open(transaction, 'w')
      f.write('Card-index: '+ fileName + '\n')
      f.write('---------------------------------------------------------\n')
      f.close()
      os.system("svn add " + transaction)
    os.system("svnlook info -r " + rev + " " + repos + " >> " + transaction)
    os.system("svnlook changed -r " + rev + " " + repos + " >> " + transaction)
    f = open(transaction, 'a')
    f.write('---------------------------------------------------------\n')
    f.close()
    #committing the issue-tracking card-index to the repository
    os.system("svn commit -m 'Issue-tracking commit' " + transaction)
    #os.system("rm -r -f /tmp/post-issues/")
  sys.exit(0)

if __name__ == '__main__':
  if len(sys.argv) < 3:
    sys.stderr.write("Usage: %s repos rev\n" % (sys.argv[0]))
  else:
    main(sys.argv[1], sys.argv[2])
