#!/usr/bin/python3
"""
Subversion pre-commit hook which currently checks that the card-index
information is consistent and correctly given.
"""
#Author: Alain Hebert, Ecole Polytechnique, 2026.

import os, sys

def main(repos, txn):
  # Recover the transaction data:
  sys.stderr.write("pre-commit: repos=" + repos + "\n")
  sys.stderr.write("pre-commit: txn=" + txn + "\n")
  message = os.popen("svnlook log -t " + txn + " " + repos).readline().strip('\n')
  #
  # Validate the commit message:
  if message[:5] != 'issue':
    sys.stderr.write ("Please begin your commit message with 'issue' characters. message=%s...\n"% \
    message[:15])
    sys.exit(1)
  try:
    cardIndexNumber =  int(message[5:11])
  except:
    sys.stderr.write ("Please begin your commit message with 'issue' characters followed" \
    +" by a six-digit index. message=%s...\n"%message[:15])
    sys.exit(1)
  newIssue = int(message[5:11])
  #
  # List of card-index
  revmax = int(os.popen("svnlook youngest " + repos).readline().strip('\n'))
  sys.stderr.write ("commit message=" + message + "\n")
  maxIssue = -1
  for k in range(revmax):
    fileName = os.popen("svnlook log -r " + str(k+1) + " " + repos).readline().strip('\n')
    maxIssue=max(maxIssue, int(fileName.split(':')[0][5:]))
  sys.stderr.write ("newIssue=" + str(newIssue) + " maxIssue=" + str(maxIssue) + "\n")
  if newIssue > maxIssue+1:
    sys.stderr.write ("The six-digit index (%d) must be <= %d. message=%s...\n"% \
    (newIssue, maxIssue+1, message[:20]))
    sys.exit(1)
  sys.exit(0)

if __name__ == '__main__':
  if len(sys.argv) < 3:
    sys.stderr.write("Usage: %s repos txn\n" % (sys.argv[0]))
  else:
    main(sys.argv[1], sys.argv[2])
