*DECK TINMIC
      SUBROUTINE TINMIC(IPMIC,IPMIC2,IPMIC3,NB,NCH,NW,ICH,IWORK,IPRT)
*
*-----------------------------------------------------------------------
*
*Purpose:
* Microscopic refueling to update the microlib (micro-depletion)
*
*Copyright:
* Copyright (C) 2010 Ecole Polytechnique de Montreal
*
*Author(s): 
* M. Guyot
*
*Parameters: input/output
* IPMIC   Adress of the L_LIBRARY in creation mode.
* IPMIC2  Adress of the fuel-map L_LIBRARY in read-only mode.
* IPMIC3  Adress of the L_LIBRARY in read-only mode, containing new
*         fuel properties.
* NB      Number of bundles
* NCH     Number of channels
* NW      Vector containing new index for the refuelling
* ICH     Number of the channel to refuel
* IWORK   Useful vector for refueling
* IPRT    Flag for printing level
*
*-----------------------------------------------------------------------
*
      USE GANLIB
*----
*  SUBROUTINE ARGUMENTS
*----
      TYPE(C_PTR) IPMIC,IPMIC2,IPMIC3
      INTEGER NB,NCH,NW(NB),ICH,IWORK(NB,2),IPRT
*----
*  LOCAL VARIABLES
*----
      TYPE(C_PTR) JPMIC,KPMIC,JPMIC2,KPMIC2,JPMIC3,KPMIC3
      PARAMETER (MAXISO=1000,NSTATE=40)
      INTEGER ISTATE(NSTATE),IB,ISO,ISO3,IMIX2,I,SHT(NB),IND(MAXISO),
     1 IND2(MAXISO),I1,I2
      LOGICAL LMIX2,EMPTY,IS_MEM,MISISO
      CHARACTER HSIGN*12,HSMG*131
*----
*  ALLOCATABLE ARRAYS
*----
      INTEGER, ALLOCATABLE, DIMENSION(:) :: BSH,NMIX2,NTYP2,NTODO2
      INTEGER, ALLOCATABLE, DIMENSION(:,:) :: NNAME2,NUSED2
      REAL, ALLOCATABLE, DIMENSION(:) :: NDENS2,NTEMP2,NVOL2
      INTEGER, ALLOCATABLE, DIMENSION(:) :: MIX2,MIX3,TODO2,TODO3,TYP2,
     1 TYP3,IPIFI
      INTEGER, ALLOCATABLE, DIMENSION(:,:) :: NAME2,NAME3,USED2,USED3,
     1 IPIFI2,IPIFI3
      REAL, ALLOCATABLE, DIMENSION(:) :: DENS2,DENS3,TEMP2,TEMP3,VOL2,
     1 VOL3,WORK
      CHARACTER(LEN=8), ALLOCATABLE, DIMENSION(:) :: HVECT
      CHARACTER(LEN=72) :: NAMLCM
      CHARACTER(LEN=12) :: NAMMY,RECNAM
      TYPE(C_PTR), ALLOCATABLE, DIMENSION(:) :: IPISO
*----
*  RECOVER DIMENSIONS FROM STATE VECTORS
*----
      CALL LCMGET(IPMIC2,'STATE-VECTOR',ISTATE)
      NISO2=ISTATE(2)
      NDFI2=ISTATE(20)
      CALL LCMGET(IPMIC3,'STATE-VECTOR',ISTATE)
      NISO3=ISTATE(2)
      NDFI3=ISTATE(20)
*----
*  SCRATCH STORAGE ALLOCATION
*----
      ALLOCATE(BSH(NB),NMIX2(NISO2),NTYP2(NISO2),NTODO2(NISO2),
     1 NNAME2(3,NISO2),NUSED2(3,NISO2),NDENS2(NISO2),NTEMP2(NISO2),
     2 NVOL2(NISO2))
      ALLOCATE(MIX2(NISO2),MIX3(NISO3),TODO2(NISO2),TODO3(NISO3),
     1 TYP2(NISO2),TYP3(NISO3),NAME2(3,NISO2),NAME3(3,NISO3),
     2 USED2(3,NISO2),USED3(3,NISO3),DENS2(NISO2),DENS3(NISO3),
     3 TEMP2(NISO2),TEMP3(NISO3),VOL2(NISO2),VOL3(NISO3))
*----
*  RECOVER INFORMATION FROM READ-ONLY MICROLIBS
*----
      CALL LCMGET(IPMIC2,'ISOTOPESMIX',MIX2)
      CALL LCMGET(IPMIC3,'ISOTOPESMIX',MIX3)
      CALL LCMGET(IPMIC2,'ISOTOPERNAME',NAME2)
      CALL LCMGET(IPMIC3,'ISOTOPERNAME',NAME3)
      CALL LCMGET(IPMIC2,'ISOTOPESUSED',USED2)
      CALL LCMGET(IPMIC3,'ISOTOPESUSED',USED3)
      CALL LCMGET(IPMIC2,'ISOTOPESDENS',DENS2)
      CALL LCMGET(IPMIC3,'ISOTOPESDENS',DENS3)
      CALL LCMGET(IPMIC2,'ISOTOPESTODO',TODO2)
      CALL LCMGET(IPMIC3,'ISOTOPESTODO',TODO3)
      CALL LCMGET(IPMIC2,'ISOTOPESTYPE',TYP2)
      CALL LCMGET(IPMIC3,'ISOTOPESTYPE',TYP3)
      CALL LCMGET(IPMIC2,'ISOTOPESTEMP',TEMP2)
      CALL LCMGET(IPMIC3,'ISOTOPESTEMP',TEMP3)
      CALL LCMGET(IPMIC2,'ISOTOPESVOL',VOL2)
      CALL LCMGET(IPMIC3,'ISOTOPESVOL',VOL3)
*----
*  RECOVER PIFI INFORMATION FROM IPMIC2
*----
      ALLOCATE(IPIFI2(NDFI2,NISO2))
      IPIFI2(:NDFI2,:NISO2)=0
      JPMIC2=LCMGID(IPMIC2,'ISOTOPESLIST')
      DO I=1,NISO2
        CALL LCMLEL(JPMIC2,I,ILONG1,ITYLCM)
        IF(ILONG1.EQ.-1) THEN
          KPMIC2=LCMGIL(JPMIC2,I)
          CALL LCMLEN(KPMIC2,'PIFI',ILONG,ITYLCM)
          IF(ILONG.EQ.NDFI2) CALL LCMGET(KPMIC2,'PIFI',IPIFI2(:,I))
        ENDIF
      ENDDO
*----
*  RECOVER PIFI INFORMATION FROM IPMIC3
*----
      ALLOCATE(IPIFI3(NDFI3,NISO3))
      IPIFI3(:NDFI3,:NISO3)=0
      JPMIC3=LCMGID(IPMIC3,'ISOTOPESLIST')
      DO I=1,NISO3
        CALL LCMLEL(JPMIC3,I,ILONG1,ITYLCM)
        IF(ILONG1.EQ.-1) THEN
          KPMIC3=LCMGIL(JPMIC3,I)
          CALL LCMLEN(KPMIC3,'PIFI',ILONG,ITYLCM)
          IF(ILONG.EQ.NDFI3) CALL LCMGET(KPMIC3,'PIFI',IPIFI3(:,I))
        ENDIF
      ENDDO
*----
*  INITIALIZE OR RECOVER IPMIC
*----
      CALL LCMLEN(IPMIC,'SIGNATURE',ILONG1,ITYLCM)
      IF(ILONG1.GT.0) THEN
        CALL LCMGTC(IPMIC,'SIGNATURE',12,HSIGN)
        IF(HSIGN.NE.'L_LIBRARY') THEN
          WRITE(HSMG,'(25H@TINMIC: IPMIC SIGNATURE=,A,13H. L_LIBRARY E,
     1    8HXPECTED.)') TRIM(HSIGN)
          CALL XABORT(HSMG)
        ENDIF
        CALL LCMGET(IPMIC,'ISOTOPESMIX',NMIX2)
        CALL LCMGET(IPMIC,'ISOTOPESDENS',NDENS2)
        CALL LCMGET(IPMIC,'ISOTOPESTYPE',NTYP2)
        CALL LCMGET(IPMIC,'ISOTOPESTODO',NTODO2)
        CALL LCMGET(IPMIC,'ISOTOPESTEMP',NTEMP2)
        CALL LCMGET(IPMIC,'ISOTOPESVOL',NVOL2)
        CALL LCMGET(IPMIC,'ISOTOPERNAME',NNAME2)
        CALL LCMGET(IPMIC,'ISOTOPESUSED',NUSED2)
        JPMIC=LCMGID(IPMIC,'ISOTOPESLIST')
      ELSE
        HSIGN='L_LIBRARY'
        CALL LCMPTC(IPMIC,'SIGNATURE',12,HSIGN)
        CALL LCMSIX(IPMIC2,'DEPL-CHAIN',1)
        CALL LCMSIX(IPMIC,'DEPL-CHAIN',1)
        CALL LCMEQU(IPMIC2,IPMIC)
        CALL LCMSIX(IPMIC,' ',2)
        CALL LCMSIX(IPMIC2,' ',2)
        CALL LCMGET(IPMIC2,'STATE-VECTOR',ISTATE)
        NG=ISTATE(3)
        NED=ISTATE(13)
        CALL LCMPUT(IPMIC,'STATE-VECTOR',NSTATE,1,ISTATE)
        IF(NED.GT.0) THEN
          ALLOCATE(HVECT(NED))
          CALL LCMGTC(IPMIC2,'ADDXSNAME-P0',8,NED,HVECT)
          CALL LCMPTC(IPMIC,'ADDXSNAME-P0',8,NED,HVECT)
          DEALLOCATE(HVECT)
        ENDIF
        ALLOCATE(WORK(NG+1))
        CALL LCMGET(IPMIC2,'ENERGY',WORK)
        CALL LCMPUT(IPMIC,'ENERGY',NG+1,2,WORK)
        DEALLOCATE(WORK)
        CALL LCMGET(IPMIC2,'ISOTOPESMIX',NMIX2)
        CALL LCMGET(IPMIC2,'ISOTOPESDENS',NDENS2)
        CALL LCMGET(IPMIC2,'ISOTOPESTYPE',NTYP2)
        CALL LCMGET(IPMIC2,'ISOTOPESTODO',NTODO2)
        CALL LCMGET(IPMIC2,'ISOTOPESTEMP',NTEMP2)
        CALL LCMGET(IPMIC2,'ISOTOPESVOL',NVOL2)
        CALL LCMGET(IPMIC2,'ISOTOPERNAME',NNAME2)
        CALL LCMGET(IPMIC2,'ISOTOPESUSED',NUSED2)
        JPMIC=LCMLID(IPMIC,'ISOTOPESLIST',NISO2)
        CALL LCMEQU(JPMIC2,JPMIC)
      ENDIF
*----
*  CHECK IF THE MIXTURES TO SHIFT EXIST IN THE MICROLIB
*----
      DO 20 IB=1,NB
        LMIX2=.FALSE.
        DO 10 ISO3=1,NISO3
          IF(MIX3(ISO3).EQ.IWORK(IB,2)) LMIX2=.TRUE.
   10   CONTINUE
        IMIX2=MIX3(ISO3)
        IF(.NOT.LMIX2) THEN
          WRITE(HSMG,'(20H@TINMIC: THE MIXTURE,I10,16H IS NOT PRESENT ,
     1    31HIN THE MICROLIB FOR THE REFUEL.)') IMIX2
          CALL XABORT(HSMG)
        ENDIF
   20 CONTINUE
*----
*  COMPUTE THE VECTORS FOR THE REFUELING
*----
*     SHT CONTAINS THE MIXTURES OF THE CHANNEL TO SHIFT
      SHT(:NB)=0
      DO I=1,NB
        SHT(I)=ICH+(I-1)*NCH
      ENDDO
*     BSH CONTAINS THE NEW MIXTURE AFTER SHIFTING
*     BSH should be full of 0, because after shifting you have no more
      DO I=1,NB
        IF(NW(I).EQ.0) THEN
          BSH(I)=0
        ELSE
          BSH(I)=SHT(NW(I))
        ENDIF
      ENDDO
*
      DO 80 IB=1,NB
        IND(:MAXISO)=0
        IND2(:MAXISO)=0
        I1=0
        I2=0
        DO 30 ISO=1,NISO2
* Numbering of indices in Fuel map L_Library in read-only mode
          IF(MIX2(ISO).EQ.SHT(IB)) THEN
            I1=I1+1
            IF(I1.GE.MAXISO) CALL XABORT('@TINMIC: NUMBER OF ISOTOPES'
     +        //' OVERFLOW(1). ')
            IND(I1)=ISO
          ENDIF
   30   CONTINUE
        IF(BSH(IB).EQ.0) THEN
*       THE PROPERTIES ARE RECOVERED FROM THE THIRD LIBRARY
          DO 40 ISO3=1,NISO3
            IF(MIX3(ISO3).EQ.IWORK(IB,2)) THEN
              I2=I2+1
              IF(I2.GE.MAXISO) CALL XABORT('@TINMIC: NUMBER OF ISOTOPES'
     +          //' OVERFLOW(2). ')
              IND2(I2)=ISO3
            ENDIF
   40     CONTINUE
          IF(I1.NE.I2) CALL XABORT('@TINMIC: WRONG NUMBER OF ISOTOPES '
     +      //'IN THE NEW MIXTURE(1). ')
          DO 50 J=1,I1
            NDENS2(IND(J))=DENS3(IND2(J))
            NTYP2(IND(J))=TYP3(IND2(J))
            NTODO2(IND(J))=TODO3(IND2(J))
            NTEMP2(IND(J))=TEMP3(IND2(J))
            NVOL2(IND(J))=VOL3(IND2(J))
            NNAME2(:,IND(J))=NAME3(:,IND2(J))
            NUSED2(:,IND(J))=USED3(:,IND2(J))
            CALL LCMLEL(JPMIC3,IND2(J),ILONG1,ITYLCM)
            IF(ILONG1.EQ.-1) THEN
              KPMIC=LCMDIL(JPMIC,IND(J))
              KPMIC3=LCMGIL(JPMIC3,IND2(J))
              CALL LCMINF(KPMIC,NAMLCM,NAMMY,EMPTY,ILONG2,IS_MEM)
              IF(ILONG2.NE.0) THEN
                DO WHILE (.NOT.EMPTY)
                  RECNAM = ' '
                  CALL LCMNXT(KPMIC,RECNAM)
                  CALL LCMDEL(KPMIC,RECNAM)
                  CALL LCMINF(KPMIC,NAMLCM,NAMMY,EMPTY,ILONG2,IS_MEM)
                ENDDO
              ENDIF

              CALL LCMEQU(KPMIC3,KPMIC)
              CALL LCMLEN(KPMIC3,'PIFI',ILONG,ITYLCM)
              IF(ILONG.EQ.NDFI3) THEN
                ALLOCATE(IPIFI(NDFI3))
                CALL LCMGET(KPMIC3,'PIFI',IPIFI)
                DO I=1,NDFI3
                  K=FINDLC(IND2(:I1),IPIFI3(I,IND2(J)))
                  IF(K.EQ.0) CALL XABORT('@TINMIC: CANNOT SET PIFI(1).')
                  IPIFI(I)=IND(K)
                ENDDO
                CALL LCMPUT(KPMIC,'PIFI',NDFI3,1,IPIFI)
                DEALLOCATE(IPIFI)
              ENDIF
            ENDIF
   50     CONTINUE
*       THE PROPERTIES ARE RECOVERED FROM THE FUEL MAP LIBRARY
        ELSE
          DO 60 ISO=1,NISO2
            IF(MIX2(ISO).EQ.BSH(IB)) THEN
              I2=I2+1
              IF(I2.GE.MAXISO) CALL XABORT('@TINMIC: NUMBER OF ISOTOPES'
     +          //' OVERFLOW(3). ')
              IND2(I2)=ISO
            ENDIF
   60     CONTINUE
          IF(I1.NE.I2) CALL XABORT('@TINMIC: WRONG NUMBER OF ISOTOPES '
     +      //'IN THE NEW MIXTURE(2). ')
          DO 70 J=1,I1
            NDENS2(IND(J))=DENS2(IND2(J))
            NTYP2(IND(J))=TYP2(IND2(J))
            NTODO2(IND(J))=TODO2(IND2(J))
            NTEMP2(IND(J))=TEMP2(IND2(J))
            NVOL2(IND(J))=VOL2(IND2(J))
            NNAME2(:,IND(J))=NAME2(:,IND2(J))
            NUSED2(:,IND(J))=USED2(:,IND2(J))
            CALL LCMLEL(JPMIC2,IND2(J),ILONG1,ITYLCM)
            IF(ILONG1.EQ.-1) THEN
              KPMIC=LCMDIL(JPMIC,IND(J))
              KPMIC2=LCMGIL(JPMIC2,IND2(J))
              CALL LCMEQU(KPMIC2,KPMIC)
              CALL LCMLEN(KPMIC2,'PIFI',ILONG,ITYLCM)
              IF(ILONG.EQ.NDFI2) THEN
                ALLOCATE(IPIFI(NDFI2))
                DO I=1,NDFI2
                  K=FINDLC(IND2(:I1),IPIFI2(I,IND2(J)))
                  IF(K.EQ.0) CALL XABORT('@TINMIC: CANNOT SET PIFI(2).')
                  IPIFI(I)=IND(K)
                ENDDO
                CALL LCMPUT(KPMIC,'PIFI',NDFI2,1,IPIFI)
                DEALLOCATE(IPIFI)
              ENDIF
            ENDIF
   70     CONTINUE
        ENDIF
   80 CONTINUE
*----
*  SAVE THE UPDATED MICROLIB
*----
      CALL LCMPUT(IPMIC,'ISOTOPESMIX',NISO2,1,NMIX2)
      CALL LCMPUT(IPMIC,'ISOTOPESDENS',NISO2,2,NDENS2)
      CALL LCMPUT(IPMIC,'ISOTOPESTYPE',NISO2,1,NTYP2)
      CALL LCMPUT(IPMIC,'ISOTOPESTODO',NISO2,1,NTODO2)
      CALL LCMPUT(IPMIC,'ISOTOPESTEMP',NISO2,2,NTEMP2)
      CALL LCMPUT(IPMIC,'ISOTOPESVOL',NISO2,2,NVOL2)
      CALL LCMPUT(IPMIC,'ISOTOPERNAME',3*NISO2,3,NNAME2)
      CALL LCMPUT(IPMIC,'ISOTOPESUSED',3*NISO2,3,NUSED2)
*----
*  CHECK FOR MISSING ISOTOPES
*----
      ALLOCATE(IPISO(NISO2))
      CALL LIBIPS(IPMIC,NISO2,IPISO)
      MISISO = .FALSE.
      DO ISO=1,NISO2
        IF(.NOT.C_ASSOCIATED(IPISO(ISO))) THEN
          IF(IPRT.GT.1) WRITE(6,100) NNAME2(:3,ISO),
     1    NMIX2(ISO)
          MISISO = .TRUE.
        ENDIF
      ENDDO
      DEALLOCATE(IPISO)
      IF(MISISO) CALL XABORT('TINMIC: MISSING STABLE ISOTOPE.')

*----
*  SCRATCH STORAGE DEALLOCATION
*----
      DEALLOCATE(IPIFI3,IPIFI2)
      DEALLOCATE(VOL3,VOL2,TEMP3,TEMP2,DENS3,DENS2)
      DEALLOCATE(USED3,USED2,NAME3,NAME2)
      DEALLOCATE(TYP3,TYP2,TODO3,TODO2,MIX3,MIX2)
      DEALLOCATE(NVOL2,NTEMP2,NDENS2,NUSED2,NNAME2,NTODO2,NTYP2,
     1 NMIX2,BSH)
      RETURN
  100 FORMAT(30H @TINMIC: ADD STABLE ISOTOPE ',3A4,12H' IN MIXTURE,
     1 I10,1H.)
      CONTAINS
      !
      FUNCTION FINDLC(ISET,ITEST) RESULT(II)
        !
        !---------------------------------------------------------------
        !
        !Purpose:
        ! function emulating the findloc function in fortran 2008
        !
        !---------------------------------------------------------------
        !
        INTEGER, DIMENSION(:), INTENT(IN) :: ISET
        INTEGER, INTENT(IN) :: ITEST
        INTEGER :: II,J1
        II=0
        DO J1=1,SIZE(ISET)
          IF(ISET(J1).EQ.ITEST) THEN
            II=J1
            EXIT
          ENDIF
        ENDDO
      END FUNCTION FINDLC
      END
